[tools]
node = "22"
python = "3.12"
java = "openjdk-23"
tflint = "latest"
rust = "1.81.0"

# plugins
aws-vault = "6.6.1"

# pipx packages
pipx = "latest"
"pipx:black" = "latest"
"pipx:flake8" = "latest"
"pipx:isort" = "latest"
"pipx:pylint" = "latest"
"pipx:poetry" = "latest"

# node packages
"npm:yarn" = "latest"

# rust packages
"cargo:rbw" = "latest"

[settings]
experimental = true
