[tools]
node = "22"
python = "3.13"
java = "openjdk-23"
tflint = "latest"
rust = "latest"
ruby = "3.3.8"
uv = "latest"

# pipx packages
pipx = "latest"
"pipx:poetry" = "latest"

# node packages
"npm:yarn" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"cargo:rbw" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
