[tools]
node = "22"
python = "3.14"
java = "openjdk-25"
tflint = "latest"
rust = "latest"
ruby = "3.3.8"
pipx = "latest"
jq = "latest"
neovim = "latest"
uv = "latest"
tfenv = "latest"
pre-commit = "latest"
ripgrep = "latest"
maven = "latest"
jbang = "latest"
"pipx:poetry" = "latest"
"npm:yarn" = "latest"
"aqua:aws/aws-cli" = { version = "latest", symlink_bins = "true" }
"aqua:exercism/cli" = "latest"
bats = "latest"
bitwarden = "latest"
chezmoi = "latest"
github-cli = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
