[tools]
node = "22"
python = "3.12"
java = "openjdk-23"
rust = "1.81.0"
tflint = "latest"

# pipx packages
pipx = "latest"
"pipx:black" = "latest"
"pipx:flake8" = "latest"
"pipx:isort" = "latest"
"pipx:pylint" = "latest"
"pipx:poetry" = "latest"

# cargo packages
"cargo:rbw" = "latest"

# node packages
"npm:yarn" = "latest"
