[tools]
node = "22"
python = "3.12"
java = "openjdk-23"
tflint = "latest"

# pipx packages
pipx = "latest"
"pipx:black" = "latest"
"pipx:flake8" = "latest"
"pipx:isort" = "latest"
"pipx:pylint" = "latest"
"pipx:poetry" = "latest"

# node packages
"npm:yarn" = "latest"

[settings]
experimental = true
